import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js v14",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>Cabecera de página</header>
        <main>{children}</main>
        <footer>Pie de página</footer>
      </body>
    </html>
  );
}
